### ISSUE TITLE
Calling an HBF function inside a function

### ISSUE THREAD

**Issue by AvirukBasak** [640-XIII/High-Brain-Fuck#3]
You could use `C` recursion to implement `function in function calls` and `recursion` in HBF.

### One method:
- You'll need to recursively call your` interpreter()` function and interpret from after `FN` to `RET`. 
- If another `CL` is spotted, you can recursively call the `interpreter()` again.
- When `RET` is spotted, you use `return` keyword. That takes you back to the previous state of commands.
- You'll need to keep track of the current command index in your `interpreter()`, and this index needs to be local to the `interpreter()`.

**Comment by 640-XIII** [comment]
Will look it up although i cannot make promises on when i will do that, university got to me and my free time.

**Comment by AvirukBasak** [comment]
Yeah I undestand
